#!/usr/bin/env sh
#
# Generate Codex agent TOML files from plugin/agents/*.md (Claude Code source of truth).
#
# For each Claude agent .md file we emit a matching <prefix><name>.toml file:
#   - frontmatter `name` → TOML `name`
#   - frontmatter `description` → TOML `description`
#   - frontmatter `model` → mapped to a Codex model + reasoning effort
#   - body (everything after the frontmatter) → `developer_instructions` triple-quoted string,
#     with a Claude→Codex swap for CLAUDE.md → AGENTS.md / CLAUDE.md
#
# Usage:
#   ./scripts/generate-codex-agents.sh --agents-src <plugin/agents> --out-dir <target> [--prefix andthen-]

set -eu

usage() {
  cat <<'EOF'
Generate Codex agent TOML files from plugin/agents/*.md.

Usage:
  ./scripts/generate-codex-agents.sh --agents-src PATH --out-dir PATH [--prefix PREFIX]

Options:
  --agents-src PATH   Source directory of Claude agent .md files (required)
  --out-dir PATH      Destination directory for generated .toml files (required)
  --prefix PREFIX     Prefix for generated file names (default: andthen-)
  -h, --help          Show this help text
EOF
}

agents_src=""
out_dir=""
prefix="andthen-"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --agents-src)
      agents_src="$2"
      shift 2
      ;;
    --out-dir)
      out_dir="$2"
      shift 2
      ;;
    --prefix)
      prefix="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$agents_src" ] || [ -z "$out_dir" ]; then
  printf 'Error: --agents-src and --out-dir are required\n\n' >&2
  usage >&2
  exit 1
fi

if [ ! -d "$agents_src" ]; then
  printf 'Error: agents source directory not found: %s\n' "$agents_src" >&2
  exit 1
fi

mkdir -p "$out_dir"

# Map Claude frontmatter model → Codex model + reasoning effort.
# Haiku  → gpt-5-mini, low   (fast lookups)
# Sonnet → gpt-5,      medium
# Opus   → gpt-5,      high
map_model() {
  case "$1" in
    haiku)  printf 'gpt-5-mini\tlow' ;;
    sonnet) printf 'gpt-5\tmedium' ;;
    opus)   printf 'gpt-5\thigh' ;;
    *)      printf 'gpt-5\tmedium' ;;
  esac
}

count=0

for agent_md in "$agents_src"/*.md; do
  [ -f "$agent_md" ] || continue

  # Parse frontmatter: between the first two lines that are exactly '---'
  frontmatter=$(awk 'BEGIN{count=0} /^---$/{count++; next} count==1{print} count>=2{exit}' "$agent_md")
  body=$(awk 'BEGIN{count=0} /^---$/{count++; next} count>=2{print}' "$agent_md")

  name=$(printf '%s\n' "$frontmatter" | awk -F': *' '/^name:/{print $2; exit}')
  description=$(printf '%s\n' "$frontmatter" | awk -F': *' '/^description:/{sub(/^description: */, ""); print; exit}')
  model=$(printf '%s\n' "$frontmatter" | awk -F': *' '/^model:/{print $2; exit}')

  if [ -z "$name" ] || [ -z "$description" ]; then
    printf 'Skipping %s: missing name or description\n' "$agent_md" >&2
    continue
  fi

  mapped=$(map_model "$model")
  codex_model=$(printf '%s' "$mapped" | cut -f1)
  codex_effort=$(printf '%s' "$mapped" | cut -f2)

  # Rewrite CLAUDE.md references to be agent-neutral (Codex reads AGENTS.md).
  # Applied to both body and description so the Codex-visible description
  # doesn't instruct the agent to read CLAUDE.md (Codex convention is AGENTS.md).
  body_rewritten=$(printf '%s' "$body" | sed 's/CLAUDE\.md/AGENTS.md \/ CLAUDE.md/g')
  description_rewritten=$(printf '%s' "$description" | sed 's/CLAUDE\.md/AGENTS.md \/ CLAUDE.md/g')

  # Escape triple quotes inside body for TOML basic-multiline safety.
  # TOML multi-line basic strings use """; body content with """ is pathological for us,
  # so we pre-substitute it (no known occurrences today).
  body_escaped=$(printf '%s' "$body_rewritten" | sed 's/"""/"" "/g')

  # TOML basic-string escaping for description: backslash must come first, then double-quote.
  description_escaped=$(printf '%s' "$description_rewritten" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')

  target="$out_dir/${prefix}${name}.toml"

  {
    printf '# Generated by scripts/generate-codex-agents.sh from plugin/agents/%s\n' "$(basename "$agent_md")"
    printf '# Do not edit by hand — edit the source .md instead.\n'
    printf '\n'
    printf 'name = "%s%s"\n' "$prefix" "$name"
    printf 'description = "%s"\n' "$description_escaped"
    printf 'model = "%s"\n' "$codex_model"
    printf 'model_reasoning_effort = "%s"\n' "$codex_effort"
    printf '\n'
    printf 'developer_instructions = """\n'
    printf '%s\n' "$body_escaped"
    printf '"""\n'
  } > "$target"

  count=$((count + 1))
done

printf 'Generated %s Codex agent files in %s\n' "$count" "$out_dir"
